### PR TITLE
Added energest in radio driver

### PR DESCRIPTION
**Pull request by Yagoor**
In this PR I added the Energest to the radio driver

### CODE REVIEW

**Comment by atiselsts** [comment]
This looks good to me. I was about to make the same PR. 
I think CPU tracking also should be added, to account the total time so that its possible to calculate the RDC in %.

Can you incorporate it, or should I make a separate PR?
https://github.com/atiselsts/iot-lab-contiki-ng/commit/7207ec57d289c4090a5a7639071e7f6bfc3b0a46

**Comment by Yagoor** [comment]
I added it in the #9.
I didn't do the ENERGEST_ON on the CPU type because this is done by the Energest Engine in the init function, but I can add it to the platform drive without any problem.

**Comment by Yagoor** [comment]
@atiselsts if you could also take a look on #10. This PR makes the RTIMER stronger against overflow. With all these PR's. The port will be much better.

**Comment by atiselsts** [comment]
Yes, I see now that you also have the CPU tracking in a separate PR.

You will need to wait for feedback from the IOT LAB maintainers. All of the PRs look reasonable as far as I can tell, but the rtimer one in particular needs to be checked by someone with a deep understanding of the platforms. Anyhow, the first priority in my mind would be to get the energest functionality to work at all, which is already achieved by PR 9 and 11 alone.

**Pull request merged**
